### ISSUE TITLE
[Feature request] Support force parameter

### ISSUE THREAD

**Issue by aledeg** [ddelnano/dredd-hooks-php#19]
At the moment, if there is already a process using the port, the hook process will fail. It could be nice to have a parameter to force the existing process to stop. This way, the dredd configuration file could look like:

``` yaml
...
language: "bin/dredd-hooks-php --force"
...
```

**Comment by ddelnano** [comment]
Yea I have been meaning to add this like we discussed about in #17.  I just haven't had the time yet.  I can probably have it done sometime this week, possibly tonight.

**Comment by aledeg** [comment]
It was just a reminder so there is a trace somewhere. I wasn't trying to rush you :)

**Comment by ddelnano** [comment]
👍 cool I appreciate that, I honestly did forget cause I meant to do it over the weekend :)

**Comment by aledeg** [comment]
If I am feeling like coding tonight, I might send a PR

**Comment by ddelnano** [comment]
Ok yea should be pretty straightforward.  Its just a change to bin/dredd-hooks-php to check for the flag and call that method you implemented if it exists.

**Comment by ddelnano** [comment]
Closing since #20 has been merged.
