### ISSUE TITLE
Dredd hook not trigger when defining multiple requests within one method

### ISSUE THREAD

**Issue by driesvints** [ddelnano/dredd-hooks-php#31]
Heya, so I've been stuck on this for several hours and no matter what I try, I can't seem to get this to work. I've defined a Dredd hook like this:

```php
Hooks::before('Events > Timetable > Return Timetable Data', function () use ($app) {
    logger()->debug('Hook triggered');
});
```

And I've defined the following Blueprint:

```
# Group Events

## Timetable [/events/{event_id}/timetable{?apikey}]

### Return Timetable Data [GET]

+ Parameters
    + event_id (required, number, `1`) - A unique identifier of the event.
    + apikey (optional, string) - The API key of the event.

+ Request Success
    + Parameters
        + event_id: 2
        + apikey: secret
+ Response 200 (application/json)

        {
            "id": 2,
            "name": "Festival",
            "timezone": "UTC",
            "time_format": 24,
            "days": []
        }

+ Request Missing Api Key
+ Response 422 (application/json)

        {
            "message": "API Key is missing"
        }

+ Request Unauthorized
    + Parameters
        + apikey: invalidkey
+ Response 401 (application/json)
    + Body
        {
            "message": "Unauthorized"
        }
```

For some reason the Hook just won't trigger and I can't figure out why. I think it's because I'm defining multiple requests under one method call. Am I doing this right in setting up the spec like this? 

The weird thing is that If I remove the last two requests like below the hook **does** pass.

```
# Group Events

## Timetable [/events/{event_id}/timetable{?apikey}]

### Return Timetable Data [GET]

+ Parameters
    + event_id (required, number, `1`) - A unique identifier of the event.
    + apikey (optional, string) - The API key of the event.

+ Request Success
    + Parameters
        + event_id: 2
        + apikey: secret
+ Response 200 (application/json)

        {
            "id": 2,
            "name": "Festival",
            "timezone": "UTC",
            "time_format": 24,
            "days": []
        }
```

It's exactly the same but with only one requests instead of three. Any ideas what I'm doing wrong here?

**Comment by ddelnano** [comment]
@driesvints is your api blueprint file indented appropriately?  From the way you pasted it I don't see any indentation for the Request, Response, etc.  As for how it treats multiple requests and responses its been a long time since I have dealt with this.  I will need to refresh my memory to make sure I know what the expected behavior is.

**Comment by driesvints** [comment]
I don't think you need to indent Request & Response. I haven't done that for any Blueprint I've written so far. Dredd can't find the Request & Response when I indent them one level.

**Comment by ddelnano** [comment]
Sorry I was thinking of the indentation needed inside the Request and Response blocks :).  I'll do some research and get back to you.

**Comment by driesvints** [comment]
Thank you so much (again) for helping out :)

**Comment by honzajavorek** [comment]
@driesvints Thanks for filing this! The thing is that when you change the API Blueprint by adding more request-response pairs, the transaction names change. You need to [use `--names` to learn what you can address in your hooks](http://dredd.readthedocs.io/en/latest/hooks/#getting-transaction-names).

```shell
$ dredd 01.apib http://example.com --names
info: Events > Timetable > Return Timetable Data > Example 1
info: Events > Timetable > Return Timetable Data > Example 2
info: Events > Timetable > Return Timetable Data > Example 3
```
vs


```shell
$ dredd 02.apib http://example.com --names
info: Events > Timetable > Return Timetable Data
```

So when you add responses, your hooks need to listen on different names:

```ruby
Hooks::before('Events > Timetable > Return Timetable Data > Example 1', function () use ($app) {
    logger()->debug('Hook triggered');
});
```

Or you can use [this trick](https://github.com/apiaryio/dredd/issues/248#issuecomment-258416765) to match all three of them.

**Comment by ddelnano** [comment]
@honzajavorek thanks for clarifying. Also php hooks have wild cards so if you can use the following to match all. 

`'Events > Timetable > Return Timetable Data *'`

**Comment by driesvints** [comment]
@honzajavorek That was it! Thank you so much for explaining this. Thank you both for your help!

**Comment by philsturgeon** [comment]
Maybe an error check could be added in Dredd for this? 

"You are trying to hook onto an action that has multiple transactions, please add transaction name to the hook." 

or 

"Did you mean 'Events > Timetable > Return Timetable Data > Example 1'" 

You get the idea.

**Comment by honzajavorek** [comment]
Hmmm... maybe if Dredd detects there is a hook for non-existing transaction
path, it could warn that hook will never get called. What do you think?

**Comment by ddelnano** [comment]
@honzajavorek how would dredd go about detecting that?  Hooks servers just process messages sent to them so dredd isn't aware of what transactions hooks are attached to.  Also in the case of the php hooks which permit wildcard matching transaction names that would cause complications for dredd detecting that.

**Comment by honzajavorek** [comment]
Hmm, that's true. Dredd doesn't know much about hooks and hook handler doesn't know much about the rest of the API description 🤔
