### ISSUE TITLE
Set hook handler to php

### ISSUE THREAD

**Issue by rathesDot** [ddelnano/dredd-hooks-php#33]
Hey,

currently the doc says that I can run tests by running

```bash
dredd apiary.apib localhost:3000 --language php --hookfiles ./hooks.php
```

Whenever I do this, I get the error that the handle cannot be found and that I should run `$ composer require ddelnano/dredd-hooks-php --dev`

No matter how often I run this, I keep getting this message ... I think, it expects me to run this globally so `composer global require ddelnano/dredd-hooks-php --dev`, because it works fine, when I reference the hook-handler directly in vendor like 

```bash
dredd apiary.apib localhost:3000 --language vendor/bin/dredd-hooks-php --hookfiles ./hooks.php
```

Is this a known issue, is the doc missing some further information or am i just doing something wrong?

**Comment by ddelnano** [comment]
I’m guessing that `~/.composer/bin` is in your PATH but not `vendor/bin`.  I wouldn’t call this a known issue per say but the docs could be more clear on this.  Dredd could also be smarter to look in the current working directory’s `vendor/bin` directory.  However, since this is the first issue I’ve seen with this I think updating the docs is probably enough.

**Comment by rathesDot** [comment]
I never had the vendor/bin in my path. Good to know that this is even possible. Would be nice if there was a note in the docs. Thank you very much for your support!

Grüße
Rathes

_____________________________________________

Lollfuß 22,
24837 Schleswig,
Germany

sachchi@rathes.de
www.rathes.de

Am 30. Jan. 2018, 04:53 +0100 schrieb Dom Del Nano <notifications@github.com>:

**Comment by ddelnano** [comment]
Can you verify that fixes it for you and then I will update the docs?

**Comment by rathesDot** [comment]
I'm wondering if I had to add the local `vendor/bin` of my project to PATH and if yes, wouldn't I have to those `vendor/bin` of every single project to PATH?

I'm normally working on a Windows Machine, on which I only have a single PATH set for composer ... Not sure how it would work on macOS or other Unix-style OS

**Comment by ddelnano** [comment]
I'm talking about a relative path so it will work in your current working directory is where your vendor folder is.  Sorry I don't have windows experience so I can't speak to that but linux / os x you would do something like

```
export PATH="$PATH:vendor/bin"
```

**Comment by rathesDot** [comment]
Yeah that means, I would have to run this on every single project I have ... That would be a solution, but only for Unix-Styles ...
In Windows there would be something like `setx path "%path%;c:\yourPath"` ... or as I did, just use `vendor/bin/dredd-hooks-php` instead of just `php` ...

I think a first good solution would be to add some additional note to the README ...

If you want, I can try to collect the information that I would expect, and you can then check, if you want to add them.

**Comment by spawnia** [comment]
I suggest adding a dredd config file to your project. This way, you do not have to specify the command line arguments every time. Another advantage of this would be that for other team members, no extra setup is required and they can just run `dredd` and do not have to worry about their path, cli arguments...

**Comment by rathesDot** [comment]
I guess we can close this issue. (not relevant for me anymore). We can always re-open if someone still has questions
