### ISSUE TITLE
Add .gitattributes with "export-ignore" options

### ISSUE THREAD

**Issue by earnaway** [ddelnano/dredd-hooks-php#4]
Any chance off adding a .gitattributes which has the "export-ignore" option for the laravel example framework? It would be handy to not include that in the download, as my IDE autocomplete often refers to classes in the example framework.
(https://www.reddit.com/r/PHP/comments/2jzp6k/i_dont_need_your_tests_in_my_production)

**Comment by ddelnano** [comment]
My bad. This is my first open source project so I had no idea that was an option. I am at work right now but I can have that fixed today or I will accept a pull request.

**Comment by earnaway** [comment]
No worries, whenever you can, that'll be great. Otherwise I'll add a pull request on Monday morning.

**Comment by ddelnano** [comment]
Fixed with #5!  Thanks for bringing that up.  I had no idea that was possible!

**Comment by earnaway** [comment]
Excellent, thanks for doing that, appreciate it.
